USE DBSysLab;

DROP TABLE khung_gio_hoat_dong_cua_hang;
DROP TABLE hinh_anh_cua_hang;
DROP TABLE mat_bang;
DROP TABLE thuong_hieu_do_luu_niem;
DROP TABLE loai_hang_do_luu_niem;
DROP TABLE dich_vu_spa;
DROP TABLE dich_vu;
DROP TABLE doanh_nghiep;
DROP TABLE hoa_don;
DROP TABLE phong_thue;
DROP TABLE don_dat_phong;
DROP TABLE hoa_don_goi_dich_vu;
DROP TABLE goi_dich_vu;
DROP TABLE khach_hang;
DROP TABLE cung_cap_vat_tu;
DROP TABLE nha_cung_cap;
DROP TABLE vat_tu;
DROP TABLE loai_vat_tu_trong_phong;
DROP TABLE loai_vat_tu;
DROP TABLE phong;
DROP TABLE chi_nhanh_co_loai_phong;
DROP TABLE thong_tin_giuong;
DROP TABLE loai_phong;
DROP TABLE khu;
DROP TABLE hinh_anh_chi_nhanh;
DROP TABLE chi_nhanh;